'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUser
    Public Property Id As String
    Public Property UserName As String
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property Discriminator As String

    Public Overridable Property AspNetUserClaims As ICollection(Of AspNetUserClaim) = New HashSet(Of AspNetUserClaim)
    Public Overridable Property AspNetUserLogins As ICollection(Of AspNetUserLogin) = New HashSet(Of AspNetUserLogin)
    Public Overridable Property AspNetRoles As ICollection(Of AspNetRole) = New HashSet(Of AspNetRole)

End Class
