'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Session
    Public Property SessionId As String
    Public Property Created As Date
    Public Property Expires As Date
    Public Property LockDate As Date
    Public Property LockCookie As Integer
    Public Property Locked As Boolean
    Public Property SessionItem As Byte()
    Public Property Flags As Integer
    Public Property Timeout As Integer

End Class
