'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPerson
    Public Property Person_id As Integer
    Public Property Person_first_name As String
    Public Property Person_last_name As String
    Public Property Person_email As String
    Public Property Person__password As String
    Public Property Person_phone As String
    Public Property Person_billing_name As String
    Public Property Person_billing_address As String
    Public Property Person_billing_phone As String
    Public Property Person_misc1 As String
    Public Property Person_misc2 As String
    Public Property Person_misc3 As String
    Public Property Person_misc4 As String
    Public Property Person_misc5 As String
    Public Property Person_tags As String

End Class
