'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblService
    Public Property Service_id As Integer
    Public Property Service_provider_id As Nullable(Of Integer)
    Public Property Service_name As String
    Public Property Service_max_number_of_participants As Nullable(Of Integer)
    Public Property Service_show_price As Nullable(Of Boolean)
    Public Property Service_price_in_cents As Nullable(Of Decimal)
    Public Property Service_length_in_minutes As Nullable(Of Integer)
    Public Property Service_display_color As String
    Public Property Service_paypal_button_html As String
    Public Property Service_show_paypal_button As Nullable(Of Integer)
    Public Property Service_description As String
    Public Property Service_is_ask_to_bring_active As Nullable(Of Boolean)
    Public Property Service_ask_ALL_to_bring As String
    Public Property Service_available_to_drop_down_value As String
    Public Property Service_recurrence_type As String
    Public Property Service_is_private_event As Nullable(Of Boolean)
    Public Property Service_changeability_policy As String
    Public Property Service_requires_check_in As String
    Public Property Service_news_or_announcement As String
    Public Property Service_history_of_client_changes As String
    Public Property Service_misc1 As String
    Public Property Service_misc2 As String
    Public Property Service_misc3 As String
    Public Property Service_misc4 As String
    Public Property Service_misc5 As String
    Public Property Service_tags As String

End Class
