'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSuperUser
    Public Property Super_user_id As Integer
    Public Property Super_user_user_name As String
    Public Property Super_user_email As String
    Public Property Super_user_password As String
    Public Property Super_user_privilege_level As Nullable(Of Integer)
    Public Property Super_user_notes As String
    Public Property Super_user_misc As String

End Class
