'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountSettings

    '''<summary>
    '''divError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtClientEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientEmails As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAreaMyInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaMyInfo As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''optNotifyAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyAll As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyOncePerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyOncePerDay As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyOncePerWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyOncePerWeek As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyOff As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''btnTestNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTestNotification As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtAreaMyScratchPad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaMyScratchPad As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
