'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountSettings

    '''<summary>
    '''optNotifyImmediately control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyImmediately As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyOnceAtEventCreationAnd2hrsBefore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyOnceAtEventCreationAnd2hrsBefore As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyOnceAtEventCreationAnd24hrsBefore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyOnceAtEventCreationAnd24hrsBefore As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optNotifyAnyChangesInLast10minutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNotifyAnyChangesInLast10minutes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''optOnlyOncePerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optOnlyOncePerDay As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''txtAreaMyScratchPad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaMyScratchPad As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
