'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAvailability
    Public Property Availability_id As Integer
    Public Property Availability_provider_id As Nullable(Of Integer)
    Public Property Availability_service_id As Nullable(Of Integer)
    Public Property Availability_client_id As Nullable(Of Integer)
    Public Property Availability_start_time As Nullable(Of Date)
    Public Property Availability_end_time As Nullable(Of Date)
    Public Property Availability_temporarily_unavailable As Nullable(Of Integer)
    Public Property Availability_notes As String
    Public Property Availability_misc1 As String
    Public Property Availability_misc2 As String
    Public Property Availability_misc3 As String
    Public Property Availability_misc4 As String
    Public Property Availability_misc5 As String
    Public Property Availability_tags As String

End Class
