'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClientReservationTable
    Public Property Client_Reservations_id As Integer
    Public Property Client_Reservations_client_id As Nullable(Of Integer)
    Public Property Client_Reservations_client_Availability_id As Nullable(Of Integer)
    Public Property Client_Reservations_Service_id As Nullable(Of Integer)
    Public Property Client_Reservations_creation_date As Nullable(Of Date)
    Public Property Client_Reservations_client_notes As String
    Public Property Client_Reservations_provider_notes As String
    Public Property Client_Reservations_recurrence_type_match As String
    Public Property Client_Reservations_what_they_said_they_will_bring As String
    Public Property Client_Reservations_what_is_specifically_asked_of_them_to_bring As String
    Public Property Client_which_provider_calendars_to_display_checked As String
    Public Property Client_Reservations_has_checked_in As Nullable(Of Boolean)
    Public Property Client_Reservations_check_in_comments As String
    Public Property Client_Reservations_misc1 As String
    Public Property Client_Reservations_misc2 As String
    Public Property Client_Reservations_misc3 As String
    Public Property Client_Reservations_misc4 As String
    Public Property Client_Reservations_misc5 As String
    Public Property Client_Reservations_tags As String

End Class
