'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblConstant
    Public Property MONTHLY_FEE As Nullable(Of Decimal)
    Public Property NUMBER_OF_FREE_DAYS As Nullable(Of Integer)
    Public Property DEFAULT_PROVIDER_INVITING_CLIENT_MESSAGE As String
    Public Property DEFAULT_CLIENT_INVITING_PROVIDER_MESSAGE_HEADER As String
    Public Property DEFAULT_CLIENT_INVITING_PROVIDER_MESSAGE_BODY As String
    Public Property PUBLIC_LISTINGS_LEVEL1_CATEGORIES As String
    Public Property PUBLIC_LISTINGS_LEVEL2_CATEGORIES As String
    Public Property DEFAULT_YOUR_PROVIDER_HAS_CHANGED_YOUR_EVENT_MESSAGE_HEADER As String
    Public Property DEFAULT_YOUR_CLIENT_HAS_USED_OR_CHANGED_SOMETHNG_CO_CALANDER_MESSAGE As String
    Public Property USE_OF_MISC_COLUMNS As String
    Public Property COLORS_TO_CYCLE_THROUGH As String
    Public Property ID As Integer

End Class
