'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProvidersClientsAndGroup
    Public Property Providers_clients_associaton_and_group_id As Integer
    Public Property Providers_clients_associaton_and_group_provider_id As Nullable(Of Integer)
    Public Property Providers_clients_associaton_and_group_client_id As Nullable(Of Integer)
    Public Property Providers_clients_associaton_and_group_groups_designator_string As String
    Public Property Providers_clients_associaton_and_group_notes_on_client As String
    Public Property Provider_ownershiop_associaton_table As String
    Public Property Provider_ownershiop_associaton_id As Nullable(Of Integer)
    Public Property Provider_ownershiop_associaton_owner_provider_id As Nullable(Of Integer)
    Public Property Provider_ownershiop_associaton_slave_provider_id As Nullable(Of Integer)
    Public Property Provider_ownershiop_associaton_commom_password As String

End Class
