'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProvider
    Public Property Provider_id As Integer
    Public Property Provider_joined_date As Nullable(Of Date)
    Public Property Provider_payment_history As String
    Public Property Provider_person_id As Nullable(Of Integer)
    Public Property Provider_display_short_name As String
    Public Property Provider_url_one_word_name As String
    Public Property Provider_password As String
    Public Property Provider_business_name As String
    Public Property Provider_create_web_page_for_me As Nullable(Of Integer)
    Public Property Provider_business_top_logo_gif_url As Byte()
    Public Property Provider_business_details_text As String
    Public Property Provider_latest_news As String
    Public Property Provider_current_announcement_message_for_client_dashboard As String
    Public Property Provider_to_email_frequency As Nullable(Of Integer)
    Public Property Provider_last_time_email_sent_to_provider As Date
    Public Property Provider_unsent_email_qeue As String
    Public Property Provider_allows_new_clients_without_approval As Nullable(Of Integer)
    Public Property Provider_required_passphrase_for_clients As String
    Public Property Provider_business_relationship_common_password As String
    Public Property Provider_scratch_pad_notes As String
    Public Property Provider_client_invitation_message As String
    Public Property Provider_use_client_invitation_in_quick_add_check_box As Nullable(Of Boolean)
    Public Property Provider_add_to_public_listing As Nullable(Of Boolean)
    Public Property Provider_public_listing_category As String
    Public Property Provider_public_listing_short_message As String
    Public Property Provider_monthly_fee_owed_in_cents As Nullable(Of Decimal)
    Public Property Provider_billing_person_paying_providers_bill As Nullable(Of Integer)
    Public Property Provider_billing_paypal_info As String
    Public Property Provider_billing_payment_history As String
    Public Property Provider_total_paid_to_date As Nullable(Of Decimal)
    Public Property Provider_notes_to_self_scrach_pad As String
    Public Property Provider_super_admin_notes As String
    Public Property Provider_sales_person_id As Nullable(Of Integer)
    Public Property Provider_sales_person_commission_percentage As Nullable(Of Double)
    Public Property Provider_flagged As Nullable(Of Boolean)
    Public Property Provider_sales_notes As String
    Public Property Provider_is_active As Nullable(Of Boolean)
    Public Property Provider_referred_emails_so_far_list As String
    Public Property Provider_referred_by As String
    Public Property Provider_referring_personal_message As String
    Public Property Provier_next_available_color_counter As Nullable(Of Integer)
    Public Property Provider_misc1 As String
    Public Property Provider_misc2 As String
    Public Property Provider_misc3 As String
    Public Property Provider_misc4 As String
    Public Property Provider_misc5 As String
    Public Property Provider_referred_by_email As String
    Public Property Provider_referral_credits_history As String
    Public Property Provider_is_searchable As Nullable(Of Boolean)
    Public Property Provider_tags As String

End Class
