'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProviderClient
    Public Property Provider_client_id As Integer
    Public Property Provider_client_owning_client As Nullable(Of Integer)
    Public Property Provider_person_id As Nullable(Of Integer)
    Public Property Provider_client_cell_phone_to_text_urgent_notification_email As String
    Public Property Provider_client_providers_notes As String
    Public Property Provider_client_billing_info As String
    Public Property Provider_client_opt_out_of_marketing_emails As Nullable(Of Boolean)
    Public Property Provider_client_amount_currently_owed As Nullable(Of Decimal)
    Public Property Provider_client_payment_history As String
    Public Property Provider_client_privilege_level As Nullable(Of Integer)
    Public Property Provider_client_is_blocked As Nullable(Of Boolean)
    Public Property Provider_client_misc1 As String
    Public Property Provider_client_misc2 As String
    Public Property Provider_client_misc3 As String
    Public Property Provider_client_misc4 As String
    Public Property Provider_client_misc5 As String
    Public Property Provider_client_tags As String
    Public Property Provider_client_groups_table As Nullable(Of Single)
    Public Property Provider_client_groups_id As Nullable(Of Integer)
    Public Property Provider_client_groups_provider_id As Nullable(Of Integer)
    Public Property Provider_client_groups As String

End Class
