'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSalesPerson
    Public Property Sales_person_id As Integer
    Public Property Sales_person_person_id As Nullable(Of Integer)
    Public Property Sales_person_induction_note As String
    Public Property Sales_person_payment_info As String
    Public Property Sales_person_payment_history As String
    Public Property Sales_person_is_active As Nullable(Of Boolean)
    Public Property Sales_person_payment_owed As Nullable(Of Decimal)
    Public Property Sales_person_super_admin_notes As String
    Public Property Sales_person_misc1 As String
    Public Property Sales_person_misc2 As String
    Public Property Sales_person_misc3 As String
    Public Property Sales_person_tags As String

End Class
