'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTransactionHistory
    Public Property Transactoin_history_id As Integer
    Public Property Transaction_time_stamp As Nullable(Of Date)
    Public Property Trannsaction_sql As String
    Public Property Transaction_originator As String
    Public Property Transaction_associated_Provider_id As Nullable(Of Integer)

End Class
