'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class WhenWhereEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WhenWhereEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblAvailabilities() As DbSet(Of tblAvailability)
    Public Overridable Property tblClientReservationTables() As DbSet(Of tblClientReservationTable)
    Public Overridable Property tblPersons() As DbSet(Of tblPerson)
    Public Overridable Property tblProviders() As DbSet(Of tblProvider)
    Public Overridable Property tblProviderClients() As DbSet(Of tblProviderClient)
    Public Overridable Property tblProvidersClientsAndGroups() As DbSet(Of tblProvidersClientsAndGroup)
    Public Overridable Property tblSalesPersons() As DbSet(Of tblSalesPerson)
    Public Overridable Property tblServices() As DbSet(Of tblService)
    Public Overridable Property tblSuperUsers() As DbSet(Of tblSuperUser)
    Public Overridable Property tblTransactionHistories() As DbSet(Of tblTransactionHistory)
    Public Overridable Property tblConstants() As DbSet(Of tblConstant)

End Class
